name: ClipFlow Build

on:
  push:
    branches: [ "release" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
            artifact-name: ClipFlow-Windows-x64
          - os: ubuntu-latest
            rid: linux-x64
            artifact-name: ClipFlow-Linux-x64
          - os: macos-latest
            rid: osx-x64
            artifact-name: ClipFlow-macOS-x64
          - os: macos-latest
            rid: osx-arm64
            artifact-name: ClipFlow-macOS-ARM64
    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ClipFlow.sln

    - name: Build
      run: dotnet build ClipFlow.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ClipFlow/ClipFlow.csproj --configuration Release --no-build --runtime ${{ matrix.rid }} --self-contained false --output ./publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact-name }}
        path: ./publish
